### ISSUE TITLE
volodya - Operators can take escrow from order after its' cancellation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dinari-judging#5]
volodya

medium

# Operators can take escrow from order after its' cancellation

## Summary
Operators can take escrow from the order after its' cancellation.
## Vulnerability Detail

Whenever the operator cancels the order he makes a refund to a user but he can still take escrow against that order when the order doesn't have any payment tokens.
```solidity
    function _cancelOrderAccounting(OrderRequest calldata order, bytes32 orderId, OrderState memory orderState)
        internal
        virtual
        override
    {
        // Prohibit cancel if escrowed payment has been taken and not returned or filled
        uint256 escrow = getOrderEscrow[orderId];
        if (orderState.remainingOrder != escrow) revert UnreturnedEscrow();

        // Standard buy order accounting
        super._cancelOrderAccounting(order, orderId, orderState);
    }

```
[issuer//DirectBuyIssuer.sol#L130](https://github.com/sherlock-audit/2023-06-dinari/blob/main/sbt-contracts/src/issuer/DirectBuyIssuer.sol#L130)
```solidity
    function takeEscrow(OrderRequest calldata orderRequest, bytes32 salt, uint256 amount)
        external
        onlyRole(OPERATOR_ROLE)
    {
        // No nonsense
        if (amount == 0) revert ZeroValue();
        // Can't take more than escrowed
        bytes32 orderId = getOrderIdFromOrderRequest(orderRequest, salt);
        uint256 escrow = getOrderEscrow[orderId];
        if (amount > escrow) revert AmountTooLarge();

        // Update escrow tracking
        getOrderEscrow[orderId] = escrow - amount;
        // Notify escrow taken
        emit EscrowTaken(orderId, orderRequest.recipient, amount);

        // Take escrowed payment
        IERC20(orderRequest.paymentToken).safeTransfer(msg.sender, amount);
    }

```
## Impact
Operators can take escrow from order after its' cancellation 

## Tool used

Manual Review

## Recommendation
```diff
    function _cancelOrderAccounting(OrderRequest calldata order, bytes32 orderId, OrderState memory orderState)
        internal
        virtual
        override
    {
        // Prohibit cancel if escrowed payment has been taken and not returned or filled
        uint256 escrow = getOrderEscrow[orderId];
        if (orderState.remainingOrder != escrow) revert UnreturnedEscrow();
+        getOrderEscrow[orderId] = 0;

        // Standard buy order accounting
        super._cancelOrderAccounting(order, orderId, orderState);
    }
```

Duplicate of #56

**Comment by Shogoki** [comment]
Escalate
This should be a duplicate of #56 
Impact and solution is the same

**Comment by sherlock-admin** [comment]
> Escalate
> This should be a duplicate of #56 
> Impact and solution is the same

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Agree with escalation

**Comment by Oot2k** [comment]
Agree with escalation

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #56

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Shogoki](https://github.com/sherlock-audit/2023-06-dinari-judging/issues/5/#issuecomment-1633355396): accepted
