### ISSUE TITLE
ctf_sec - The percentage fee can vary during the life of a sell order

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dinari-judging#58]
ctf_sec

medium

# The percentage fee can vary during the life of a sell order

## Summary
Sell orders can be filled partially. Upon each partial fill, the percentage fee is calculated based on the current fee percentage set in the `OrderFees.sol` contract. Therefore, any change to the percentage fee rate retroactively applies to all active sell orders.

## Vulnerability Detail
Buy orders do not suffer from this issue, as they have the percentage fee taken out upon requesting the order. This ensures that future changes to the percentage fee rate do not affect active orders.

A user can create a sell order while the percentage fee is **1%**. If Dinari changes it so that the percentage fee is now **10%**, then it will apply to the already active order.

## Impact
- Users will be exposed to different percentage fees than expected when requesting the order

## Code Snippet
https://github.com/sherlock-audit/2023-06-dinari/blob/4851cb7ebc86a7bc26b8d0d399a7dd7f9520f393/sbt-contracts/src/issuer/SellOrderProcessor.sol#L92-L101

## Tool used
Manual Review

## Recommendation
The percentage fee rate should be stamped when the sell order is requested. Future changes to the current percentage fee should not affect existing orders.

**Comment by Delvir0** [comment]
Escalate
This should be a valid low since it's a design choice and/ or the impact is low. 

1. Changing the fee percentage: It is to assume that the owner/ admin does not perform mistakes or malicious actions, like raising the percentage by a lot at once.
2. Impact: scenario's, as the watson also mentions, impacted are only the ones where their order is partly filled.

I agree that this is something that the user could be impacted by and not account for. Contrariwise, given that (a) the percentage fee will not be raised by a lot (b) this only accounts for partly filled orders the impact is too low for Sherlocks criteria to be at a severity of Medium.

**Comment by sherlock-admin** [comment]
> Escalate
> This should be a valid low since it's a design choice and/ or the impact is low. 
> 
> 1. Changing the fee percentage: It is to assume that the owner/ admin does not perform mistakes or malicious actions, like raising the percentage by a lot at once.
> 2. Impact: scenario's, as the watson also mentions, impacted are only the ones where their order is partly filled.
> 
> I agree that this is something that the user could be impacted by and not account for. Contrariwise, given that (a) the percentage fee will not be raised by a lot (b) this only accounts for partly filled orders the impact is too low for Sherlocks criteria to be at a severity of Medium.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Agree with escalation.

**Comment by Oot2k** [comment]
Agree with escalation

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This issue can be considered a valid low

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Delvir0](https://github.com/sherlock-audit/2023-06-dinari-judging/issues/58/#issuecomment-1633986451): accepted

**Comment by ctf-sec** [comment]
@jaketimothy 

[for issue 109 ](https://github.com/dinaricrypto/sbt-contracts/issues/109)

the link https://github.com/dinaricrypto/sbt-contracts/tree/feat/percentageFee has 404 error

**Comment by ctf-sec** [comment]
fix looks ok
