### ISSUE TITLE
0xyPhilic - Lack of anti-slippage measure exposes users

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dinari-judging#90]
0xyPhilic

medium

# Lack of anti-slippage measure exposes users

## Summary

Any user can `requestOrder` either to Buy or Sell an off-chain security asset by providing USDC. The `requestOrder` function accepts a struct `OrderRequest` in which the following information is provided by the user: recipient, assetToken, paymentToken, quantityIn, price. After the accounting is done which simply calculates the fees that the user is supposed to pay and substract them from the `quantityIn` the final Order is saved. Once the order is live a Keeper can pick up the order and either fill it fully or partially. Orders are executed in the order of their submissions as confirmed by the protocol team on Discord. To fill the order the Keeper needs to pass the order it is filling as well as the `fillAmount` and `receivedAmount`, where the `fillAmount` is the amount of USDC/USDT supplied as `quantityIn` and the `receivedAmount` is the amount of dShare representing the actual security purchase.

## Vulnerability Detail

The problem is that the `price` parameter passed by the user during order request is never used. The purpose of the `price` parameter is to act as an anti-slippage measure for the user in order to avoid getting his/hers order filled at unfavourable rate, however during the `fillOrder` there are no checks if the conditions set by the user are satisfied. This could lead to orders being executed at an undesirable price, thus causing loss of value for the users. Lets' imagine the following scenario:

Alice posts 900 USDC as `quantityIn` to buy TESLA stock which is currently traded at 300$, so Alice sets a price to buy at 320$ as example in order to leave some room until her order is executed. However there are many orders before Alice's so by the time it
s her orders turn the price of TESLA has skyrocketed to 500$. The Keeper would calculate that for 900 USDC they can buy 1.8 TESLA stocks, so the Keeper would call the `fillOrder` function with `fillAmount` = 900 (entirely filling the order) and `receiveAmount` = 1.8. The order fill would be executed and 1.8 dShares representing 1.8 TESLA stocks will be minted for Alice and the 900 USDC will be transferred out of the contract and to the Keeper. 

As we can see although Alice have set slippage by specifying a max_price per say at which she desires her order to still be executed, the condition is not taken into account and the order is executed at any arbitrary price. 

## Impact

Loss of value for users 

## Code Snippet

RequestOrder where `price` is specified: https://github.com/sherlock-audit/2023-06-dinari/blob/main/sbt-contracts/src/issuer/OrderProcessor.sol#L244-L264
FillOrder Accounting: https://github.com/sherlock-audit/2023-06-dinari/blob/main/sbt-contracts/src/issuer/BuyOrderIssuer.sol#L146-L158

## Tool used

Manual Review

## Recommendation

Make sure to enforce that the `receivedAmount` during `fillOrder` corresponds to the expected `min_amount`, i.e. for the above example Alice would expect a minimum of 2.8125 TESLA stocks. If the `receivedAmount` is less than that the order fill should not happen - either postpone the fill of the order or if that would cause problems for the Keeper, best would be to directly `cancelOrder`.

**Comment by 0xyPhilic** [comment]
Escalate

I am not sure why `slippage` related issues are considered `invalid`, following the Sherlock Criteria for Issue Validity, which states: 

**Slippage related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid high**

There is the option for the user to define a `price` which is never used. This gives the users a false expectation when it comes to amount of dShares they would receive for their order.

Although regular brokerage companies execute market orders without regard to the price, we can't compare their way of working to the current protocol implementation, since regular brokerage companies have way more computation resources at their disposal and don't suffer from network congestions. 

The protocol team has stated in Discord that the order execution is done based on the order submission. So if we have a situation where there are 1000 orders before my order this means  that from timeA when the 1st order is executed and timeB when my order is executed there could be significant change in the security price causing a loss for me.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> I am not sure why `slippage` related issues are considered `invalid`, following the Sherlock Criteria for Issue Validity, which states: 
> 
> **Slippage related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid high**
> 
> There is the option for the user to define a `price` which is never used. This gives the users a false expectation when it comes to amount of dShares they would receive for their order.
> 
> Although regular brokerage companies execute market orders without regard to the price, we can't compare their way of working to the current protocol implementation, since regular brokerage companies have way more computation resources at their disposal and don't suffer from network congestions. 
> 
> The protocol team has stated in Discord that the order execution is done based on the order submission. So if we have a situation where there are 1000 orders before my order this means  that from timeA when the 1st order is executed and timeB when my order is executed there could be significant change in the security price causing a loss for me. 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by talllo** [comment]
#20 and a bunch of others are dupes of this. should be valid according to my convo with the sponsor 
![image](https://github.com/sherlock-audit/2023-06-dinari-judging/assets/46828872/7b86b313-b6b7-4f1b-910e-215cbc6490d7)

**Comment by TradMod** [comment]
I agree with you but I think its kinda late. You should have raised an escalation for this during the escalation period. I wanted to raise an escalation for this (I had submitted a similar finding) but sherlock new rules didn't allow me

**Comment by talllo** [comment]
yeah, my bad. I somehow completely missed a notification for the escalation period. I've dmed the judge and lsr so there still might be a chance. its most almost certainly a valid issue and should be worth another look
